### PR TITLE
Fix for issue #61

### PR DESCRIPTION
**Pull request by chickahoona**
Fix for issue #61

### CODE REVIEW

**Comment by ewels** [comment]
Nice spot, thanks! Minor pedantic thing, but I usually use the `cbtbc` prefix. For consistency's sake, would you mind swapping `carousel-item-` for `cptbc-item-` please?

Cheers,

Phil

**Comment by chickahoona** [comment]
Done

**Comment by ewels** [comment]
Thanks!

**Comment by ewels** [comment]
Hi @chickahoona - apologies for the delay. I've just pushed the latest version of the plugin to wordpress.org with your changes: https://wordpress.org/plugins/cpt-bootstrap-carousel/

Thanks again!

**Pull request merged**
