### PR TITLE
Added German localization and Dashicons menu icon 

### PR DESCRIPTION
**Pull request by stefan-meier**

### CODE REVIEW

**Comment by ewels** [comment]
Fantastic! Vielen dank @stefan-meier!

**Comment by stefan-meier** [comment]
You're very welcome @ewels! Thank you for the great plugin!

**Comment by ewels** [comment]
Hi @stefan-meier - apologies for the delay. I've just pushed the latest version of the plugin to wordpress.org with your changes: https://wordpress.org/plugins/cpt-bootstrap-carousel/

Thanks again!

**Comment by stefan-meier** [comment]
Hi @ewels, you're welcome! Thanks for the info.

**Pull request merged**
